"""Declarative base, naming convention and shared column mixins.

The naming convention matches ``SCHEMA.md`` DDL conventions so that Alembic
autogenerate produces indexes/constraints with the exact names already
documented (``idx_*``, ``uq_*``, ``fk_*``, ``ck_*``). This avoids drift
between the designed DDL and the generated migration.
"""

from __future__ import annotations

from datetime import date, datetime, timezone

from sqlalchemy import (
    MetaData,
    TIMESTAMP,
    func,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    declarative_mixin,
    mapped_column,
)


def _utcnow() -> datetime:
    """Return the current UTC datetime (timezone-aware)."""
    return datetime.now(timezone.utc)


# Naming convention applied to all constraints/indexes generated by Alembic.
# Names that already appear in SCHEMA.md (`idx_*`, `uq_*`) take precedence
# when declared explicitly in the models.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Project-wide SQLAlchemy declarative base.

    All ORM models inherit from this class. ``metadata`` uses the shared
    naming convention so Alembic-generated constraints follow the
    convention used in ``docs/SCHEMA.md``.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


@declarative_mixin
class TimestampMixin:
    """``created_at`` / ``updated_at`` columns for mutable tables.

    Per ``SCHEMA.md`` §14, this mixin MUST NOT be applied to ``predictions``
    or ``prediction_explanations`` (immutable / append-only). The
    ``updated_at`` column is auto-refreshed by the ``trg_set_updated_at``
    trigger installed by the initial migration for every mutable table.
    """

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


@declarative_mixin
class ExternalIdMixin:
    """``external_id`` UNIQUE column that stores the provider's identifier.

    Decouples our internal ``id`` (BIGSERIAL) from the data source. The
    unique constraint name follows the naming convention
    (``uq_<table>_external_id``).
    """

    external_id: Mapped[int] = mapped_column(
        unique=True,
        nullable=False,
        index=False,
    )


@declarative_mixin
class CreatedAtMixin:
    """Single ``created_at`` for append-only tables (no ``updated_at``).

    Used by ``predictions`` and ``prediction_explanations``.
    """

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


def utcnow() -> datetime:
    """Public alias of the internal utcnow helper, used by tests/factories."""
    return _utcnow()


__all__ = [
    "Base",
    "CreatedAtMixin",
    "ExternalIdMixin",
    "NAMING_CONVENTION",
    "TimestampMixin",
    "utcnow",
]
